# Generated by Django 3.1.1 on 2021-05-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': "Course's",
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=30)),
                ('course_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsoftdelete.course')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': "Student's",
            },
        ),
    ]
