# Generated by Django 3.1.1 on 2021-05-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=150)),
                ('traceback', models.TextField()),
                ('remote_address', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exception', models.TextField()),
            ],
            options={
                'verbose_name': 'Exception Log',
                'verbose_name_plural': 'Exception Logs',
                'db_table': 'exception_logs',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=500)),
                ('response_status', models.IntegerField()),
                ('request_body', models.TextField(null=True)),
                ('remote_address', models.CharField(max_length=50)),
                ('server_hostname', models.CharField(max_length=50)),
                ('run_time', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'db_table': 'request_logs',
            },
        ),
    ]
